### ISSUE TITLE
After resizing avif image file size show same size as original file size

### ISSUE THREAD

**Issue by Kevin301099** [kornelski/avif-serialize#7]
no decreasing in file size after changing resolution of avif image
<img width="547" alt="Screenshot 2023-09-16 at 2 57 33 AM" src="https://github.com/kornelski/avif-serialize/assets/49025655/071d78be-84b5-429a-9885-f0817e5743d4">

**Comment by kornelski** [comment]
This library is a low-level component, and isn't really responsible for image resizing.

If you're changed resolution using Apple's Preview.app, you may have edited DPI metadata instead of changing the image.

**Comment by Kevin301099** [comment]
any suggestion ?

how to resize AVIF image in rust ?

**Comment by baumanj** [comment]
> any suggestion ?
> 
> how to resize AVIF image in rust ?

Try https://crates.io/crates/image

**Comment by Kevin301099** [comment]
ok, thank you.

**Comment by kornelski** [comment]
Oh, I think I know what you mean now: this library takes width and height. These properties are supposed to reflect what the size of AV1 data is, not change it. 

See the https://lib.rs/ravif crate for encoding AV1 from scratch.
